<?php
set_time_limit(0);
require_once dirname(__DIR__) . DIRECTORY_SEPARATOR . 'services' . DIRECTORY_SEPARATOR . 'Auth.php';
Auth::start_session();
require_once dirname(__DIR__) . DIRECTORY_SEPARATOR . 'sqlite' . DIRECTORY_SEPARATOR . 'db.php';
require_once __DIR__ . '/../services/AIService.php';
require_once __DIR__ . '/../services/Logger.php';

header('Content-Type: application/json');

$resume_id = intval($_GET['id'] ?? $_POST['id'] ?? 0);
$user_id = Auth::user_id();
$req_start = microtime(true);

log_info('process_resume', "=== Generation request start ===", [
    'resume_id' => $resume_id,
    'user_id'   => $user_id,
    'method'    => $_SERVER['REQUEST_METHOD']
]);

if (!$resume_id) {
    log_warn('process_resume', 'Missing resume id in request');
    echo json_encode(['success' => false, 'error' => 'Missing resume id']);
    exit;
}

$stmt = $db->prepare("SELECT * FROM resumes WHERE id = ? AND user_id = ?");
$stmt->execute([$resume_id, $user_id]);
$resume = $stmt->fetch();

if (!$resume) {
    log_warn('process_resume', 'Resume not found', ['resume_id' => $resume_id, 'user_id' => $user_id]);
    echo json_encode(['success' => false, 'error' => 'Resume not found']);
    exit;
}

log_info('process_resume', 'Resume loaded', [
    'job_profile' => $resume['job_profile'],
    'template'    => $resume['template'],
    'status'      => $resume['status'],
    'has_ai_content' => !empty($resume['ai_content'])
]);

if ($resume['status'] === 'completed' && !empty($resume['ai_content'])) {
    log_info('process_resume', 'Resume already completed; skipping');
    echo json_encode(['success' => true, 'status' => 'completed']);
    exit;
}

if ($resume['status'] === 'generating') {
    log_info('process_resume', 'Resume already being generated by another request; returning processing');
    echo json_encode(['success' => true, 'status' => 'processing', 'message' => 'Resume is being generated...']);
    exit;
}

if ($resume['status'] === 'completed' && empty($resume['ai_content'])) {
    log_warn('process_resume', 'Resume completed but has empty ai_content; resetting to pending for regeneration');
    $db->prepare("UPDATE resumes SET status = 'pending' WHERE id = ?")->execute([$resume_id]);
    $resume['status'] = 'pending';
}

$user_stmt = $db->prepare("SELECT * FROM users WHERE id = ?");
$user_stmt->execute([$user_id]);
$student = $user_stmt->fetch();

$beta_credits = Auth::beta_global_credits();
$is_beta_override = $beta_credits !== null;
$available_credits = $is_beta_override ? $beta_credits : (int)($student['ai_credits'] ?? 0);

if ($available_credits <= 0) {
    $err = 'No AI credits remaining';
    log_warn('process_resume', $err, ['user_id' => $user_id, 'credits' => $available_credits]);
    $db->prepare("UPDATE resumes SET status = 'failed', last_error = ? WHERE id = ?")->execute([$err, $resume_id]);
    echo json_encode(['success' => false, 'error' => $err, 'no_credits' => true]);
    exit;
}

$db->prepare("UPDATE resumes SET status = 'generating', last_error = NULL WHERE id = ?")->execute([$resume_id]);

try {
    $stmt_p = $db->prepare("SELECT full_name, email, phone, city, linkedin, github, portfolio, summary FROM profile_personal WHERE user_id = ? LIMIT 1");
    $stmt_p->execute([$user_id]);
    $personal = $stmt_p->fetch() ?: null;

    $stmt_a = $db->prepare("SELECT degree, institution, board_university, start_year, end_year, grade, description FROM profile_academics WHERE user_id = ? ORDER BY start_year DESC");
    $stmt_a->execute([$user_id]);
    $academics = $stmt_a->fetchAll();

    $stmt_e = $db->prepare("SELECT job_title, company, location, start_date, end_date, is_current, description FROM profile_experience WHERE user_id = ? ORDER BY start_date DESC");
    $stmt_e->execute([$user_id]);
    $experience = $stmt_e->fetchAll();

    $stmt_s = $db->prepare("SELECT skill_name, proficiency FROM profile_skills WHERE user_id = ? ORDER BY id DESC LIMIT 25");
    $stmt_s->execute([$user_id]);
    $skills = $stmt_s->fetchAll();

    $stmt_pr = $db->prepare("SELECT title, tech_stack, description FROM profile_projects WHERE user_id = ? LIMIT 3");
    $stmt_pr->execute([$user_id]);
    $projects = $stmt_pr->fetchAll();

    $stmt_ach = $db->prepare("SELECT title, issuer, date FROM profile_achievements WHERE user_id = ?");
    $stmt_ach->execute([$user_id]);
    $achievements = $stmt_ach->fetchAll();
} catch (Exception $e) {
    log_error('process_resume', 'Profile query failed', ['error' => $e->getMessage()]);
    $db->prepare("UPDATE resumes SET status = 'failed', last_error = ? WHERE id = ?")->execute([$e->getMessage(), $resume_id]);
    echo json_encode(['success' => false, 'error' => 'Profile query failed: ' . $e->getMessage()]);
    exit;
}

log_info('process_resume', 'Profile data fetched', [
    'has_personal'    => (bool)$personal,
    'personal_name'   => $personal['full_name'] ?? null,
    'academics_count' => count($academics),
    'experience_count'=> count($experience),
    'skills_count'    => count($skills),
    'projects_count'  => count($projects),
    'achievements_count' => count($achievements)
]);

$profile_completeness = (int)(bool)$personal + (count($academics) > 0 ? 1 : 0) + (count($experience) > 0 ? 1 : 0) + (count($skills) > 0 ? 1 : 0);
if ($profile_completeness < 2) {
    $err = 'Your profile is empty or incomplete. Please fill in your personal info, education, experience, and skills before generating a resume.';
    log_warn('process_resume', 'Profile incomplete â€” short-circuiting before AI call', [
        'profile_completeness_score' => $profile_completeness . '/4',
        'missing' => array_filter([
            'personal'    => !(bool)$personal,
            'academics'   => count($academics) === 0,
            'experience'  => count($experience) === 0,
            'skills'      => count($skills) === 0
        ])
    ]);
    $db->prepare("UPDATE resumes SET status = 'failed', last_error = ? WHERE id = ?")->execute([$err, $resume_id]);
    echo json_encode([
        'success' => false,
        'error' => $err,
        'empty_profile' => true,
        'redirect' => '?page=profile',
        'log' => 'logs/ai.log'
    ]);
    exit;
}

$profile_name = $resume['job_profile'];

$context = "Job Profile: $profile_name\n\n";
$context .= "Name: " . ($personal['full_name'] ?? '') . "\n";
$context .= "Email: " . ($personal['email'] ?? '') . "\n";
$context .= "Phone: " . ($personal['phone'] ?? '') . "\n";
$context .= "Location: " . ($personal['city'] ?? '') . "\n";
$context .= "LinkedIn: " . ($personal['linkedin'] ?? '') . "\n";
$context .= "GitHub: " . ($personal['github'] ?? '') . "\n";
$context .= "Portfolio: " . ($personal['portfolio'] ?? '') . "\n";
$context .= "Summary: " . ($personal['summary'] ?? '') . "\n\n";

if (!empty($academics)) {
    $context .= "Education:\n";
    foreach ($academics as $a) {
        $context .= "- {$a['degree']} from {$a['institution']} ({$a['start_year']}-{$a['end_year']}) Grade: {$a['grade']}\n";
    }
    $context .= "\n";
}

if (!empty($experience)) {
    $context .= "Experience:\n";
    foreach ($experience as $e) {
        $end = $e['is_current'] ? 'Present' : ($e['end_date'] ?: 'N/A');
        $context .= "- {$e['job_title']} at {$e['company']}, {$e['location']} ({$e['start_date']}-{$end})\n";
        if (!empty($e['description'])) {
            $context .= "  " . substr($e['description'], 0, 400) . "\n";
        }
    }
    $context .= "\n";
}

if (!empty($skills)) {
    $context .= "Skills: " . implode(', ', array_column($skills, 'skill_name')) . "\n\n";
}

if (!empty($projects)) {
    $context .= "Projects:\n";
    foreach ($projects as $p) {
        $context .= "- {$p['title']} ({$p['tech_stack']}): " . substr($p['description'], 0, 250) . "\n";
    }
    $context .= "\n";
}

if (!empty($achievements)) {
    $context .= "Achievements:\n";
    foreach ($achievements as $a) {
        $context .= "- {$a['title']}";
        if (!empty($a['issuer'])) $context .= " from {$a['issuer']}";
        if (!empty($a['date'])) $context .= " ({$a['date']})";
        $context .= "\n";
    }
}

log_debug('process_resume', 'Built context', [
    'context_length' => strlen($context),
    'context_preview' => substr($context, 0, 400)
]);

$rules = 'Return ONLY valid JSON, no markdown, no code blocks.

CRITICAL RULES:
1. Use ONLY the data provided in the Context. Do NOT invent or fabricate ANY information.
2. Header fields must come EXACTLY from the Candidate Information.
3. Experience must use the EXACT job titles, companies, locations, dates, and descriptions provided.
4. Academics must use the EXACT degree, institution, dates, and grades provided.
5. Skills must use the EXACT skill names provided.
6. Projects must use the EXACT titles, tech stacks, and descriptions provided.
7. Achievements must use the EXACT titles and issuers provided.
8. Summary: Write 2-3 sentences based ONLY on the candidate real experience and skills.
9. Experience descriptions: Keep original content, refine wording for clarity only.

JSON Structure:
{
    "header": {"full_name": "EXACT", "job_title": "job profile name", "email": "EXACT", "phone": "EXACT", "location": "EXACT", "linkedin": "EXACT or null", "github": "EXACT or null", "portfolio": "EXACT or null"},
    "summary": "2-3 sentences based on real experience",
    "experience": [{"job_title": "string", "company": "string", "location": "string", "start_date": "string", "end_date": "string", "is_current": boolean, "description": "string"}],
    "academics": [{"degree": "string", "institution": "string", "board_university": "string", "start_year": "string", "end_year": "string", "grade": "string", "description": "string"}],
    "skills": [{"skill_name": "string", "proficiency": "Beginner or Intermediate or Advanced or Expert"}],
    "projects": [{"title": "string", "tech_stack": "string", "url": "string or null", "start_date": "string", "end_date": "string", "description": "string"}],
    "achievements": [{"title": "string", "issuer": "string", "date": "string", "description": "string"}],
    "generated_for": "job profile name",
    "generated_at": "ISO timestamp"
}';

$user_prompt = "Generate a resume JSON for the {$profile_name} position using ONLY the candidate data above. Reorder skills and projects by relevance to {$profile_name}. Write summary based on actual experience.";

log_info('process_resume', 'Calling AI service', [
    'model'   => env('AI_MODEL'),
    'max_tokens' => 3000,
    'rules_len' => strlen($rules),
    'context_len' => strlen($context),
    'user_prompt' => $user_prompt
]);

$ai_start = microtime(true);
try {
    $ai_content = ai($rules, $context, $user_prompt);
    $ai_duration = round(microtime(true) - $ai_start, 2);

    log_info('process_resume', 'AI responded', [
        'duration_sec' => $ai_duration,
        'response_length' => strlen($ai_content),
        'response_preview' => substr($ai_content, 0, 500),
        'response_tail' => strlen($ai_content) > 500 ? substr($ai_content, -200) : null
    ]);

    $decoded = json_decode($ai_content, true);
    if (json_last_error() !== JSON_ERROR_NONE || !is_array($decoded)) {
        $err = 'AI returned invalid JSON: ' . json_last_error_msg() . ' | first 200 chars: ' . substr($ai_content, 0, 200);
        log_error('process_resume', $err);
        throw new Exception($err);
    }

    $name_present  = !empty($decoded['header']['full_name']);
    $email_present = !empty($decoded['header']['email']);
    $exp_count     = count($decoded['experience'] ?? []);
    $skill_count   = count($decoded['skills'] ?? []);
    $has_real_data = $name_present || $email_present || $exp_count > 0 || $skill_count > 0;

    log_info('process_resume', 'Parsed AI response', [
        'name'  => $decoded['header']['full_name'] ?? null,
        'email' => $decoded['header']['email'] ?? null,
        'experience_count' => $exp_count,
        'skills_count'     => $skill_count,
        'projects_count'   => count($decoded['projects'] ?? []),
        'has_real_data'    => $has_real_data
    ]);

    if (!$has_real_data) {
        $err = 'No profile data found. Please fill in your Personal Info, Education, Experience, and Skills first, then try again.';
        log_error('process_resume', 'AI returned empty template â€” profile is empty', [
            'raw_response' => $ai_content,
            'profile_summary' => [
                'has_personal' => (bool)$personal,
                'academics'    => count($academics),
                'experience'   => count($experience),
                'skills'       => count($skills),
                'projects'     => count($projects),
                'achievements' => count($achievements)
            ]
        ]);
        $db->prepare("UPDATE resumes SET status = 'failed', last_error = ? WHERE id = ?")->execute([$err, $resume_id]);
        if (!$is_beta_override) {
            $db->prepare("UPDATE users SET ai_credits = ai_credits + 1 WHERE id = ?")->execute([$user_id]);
        }
        echo json_encode([
            'success' => false,
            'error' => $err,
            'refunded' => true,
            'empty_profile' => true,
            'redirect' => '?page=profile',
            'log' => 'logs/ai.log'
        ]);
        exit;
    }

    $db->prepare("UPDATE resumes SET ai_content = ?, status = 'completed', last_error = NULL WHERE id = ?")
       ->execute([$ai_content, $resume_id]);

    if (!$is_beta_override) {
        $db->prepare("UPDATE users SET ai_credits = ai_credits - 1 WHERE id = ?")->execute([$user_id]);
    }

    $total = round(microtime(true) - $req_start, 2);
    log_info('process_resume', '=== Generation SUCCESS ===', [
        'total_sec' => $total,
        'credits_remaining' => $is_beta_override ? $beta_credits : ((int)$student['ai_credits'] - 1)
    ]);

    echo json_encode([
        'success' => true,
        'status' => 'completed',
        'credits_remaining' => $student['ai_credits'] - 1
    ]);

} catch (Exception $e) {
    $total = round(microtime(true) - $req_start, 2);
    $err = $e->getMessage();
    log_error('process_resume', '=== Generation FAILED ===', [
        'total_sec' => $total,
        'error' => $err,
        'trace' => $e->getTraceAsString()
    ]);
    $db->prepare("UPDATE resumes SET status = 'failed', last_error = ? WHERE id = ?")->execute([$err, $resume_id]);
    echo json_encode([
        'success' => false,
        'error' => 'AI generation failed: ' . $err,
        'log' => 'logs/ai.log'
    ]);
}
